name: Deploy Discord Bot to Production

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [OryzaDiscordBot]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Restart Bot with pm2
      run: pm2 restart OryzaDiscordBot
